# prophet_forecast.py
from prophet import Prophet
import pandas as pd

def prophet_forecast(series, periods=7):
    # series: pandas Series with DatetimeIndex of daily close
    df = series.reset_index()
    df.columns = ["ds","y"]
    m = Prophet(daily_seasonality=True, changepoint_prior_scale=0.5)
    m.fit(df)
    future = m.make_future_dataframe(periods=periods)
    forecast = m.predict(future)
    return forecast  # includes yhat, yhat_lower, yhat_upper
if __name__ == "__main__":
    # 1. Load parquet file generated by your ingestion pipeline
    prices = pd.read_parquet("prices_daily.parquet")

    # 2. Check available coin columns
    print("Available coins:", list(prices.columns)[:10])

    # 3. Run forecast for Bitcoin
    if "bitcoin" in prices.columns:
        btc_forecast = prophet_forecast(prices["bitcoin"], periods=7)

        print("\nBitcoin 7-day forecast:")
        print(btc_forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail())
    else:
        print("Error: 'bitcoin' column not found in prices dataframe.")

